Added the popup window functionality
AshwinCarvalho999/Portfolio-details-popup-window pull request #1
Opened 2022-09-06 14:01 UTC by AshwinCarvalho999

Added index.html
Added style.css
Added Linters
Added script.js
Added  style.css
Added Popup Window for card section so that users can interact and navigate all details of the project
Added .gitignore file to ignore node_modules file
Added Readme file

2022-09-06 15:32 UTC, FrederickMih requested changes
Hi @AshwinCarvalho999 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No Linter error :+1: 
- PR has a title and summary :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-06 15:32 UTC, FrederickMih commented on script.js
> +  },
- [ ] Based on the requirements of this project, the popup should follow the design in Figma for both desktop and mobile versions. Please compare the screenshots below for the desktop versions and make the necessary changes. You'll need to align those buttons and text exactly as seen in the original screenshot below. 

| Yours | Figma |
| --- | --- |
| ![Screenshot from 2022-09-06 16-06-24](https://user-images.githubusercontent.com/63087491/188674387-0ff7acc7-5501-4479-b246-0e3cd7af02d6.png) | ![Screenshot from 2022-09-06 16-02-23](https://user-images.githubusercontent.com/63087491/188674441-7e0a4b29-0115-457b-9093-6399504532b7.png) |

2022-09-07 09:21 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @AshwinCarvalho999 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ Good UI

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 09:21 UTC, codepantha commented on style.css
> +}
- [ ] While implementing the required changes for the popup modal on desktop devices, you have broken the popup modal design for mobile devices. Kindly ensure that the width on mobile devices corresponds to the given figma design template 👍 
## Your Previous Design
![](https://user-images.githubusercontent.com/46839548/188840253-dad6d276-c8de-4bac-9e67-853887a8e79c.png)
## Your Current Design
![image](https://user-images.githubusercontent.com/46839548/188841611-176cd116-4b2a-431f-9291-1808872e5aea.png)

2022-09-07 09:29 UTC, AshwinCarvalho999 commented
Done.

On Wed, Sep 7, 2022, 2:51 PM Eze Promise ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: REQUIRES CHANGES ♻️ Hi @AshwinCarvalho999
> <https://github.com/AshwinCarvalho999> 👋,
>
> Great work on making the changes requested by the previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which haven't been addressed yet.
> Highlights 🎯
>
> ✔️ Descriptive PR
> ✔️ Good commit history
> ✔️ Good UI
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/AshwinCarvalho999/Portfolio-details-popup-window/pull/1#discussion_r964598693>
> :
>
> > +.details {
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  padding: 16px;
>
> +  background-color: white;
>
> +  color: #e05304;
>
> +  width: 59%;
>
> +  position: relative;
>
> +  margin: 2% 0;
>
> +  gap: 16px;
>
> +}
>
>
>
>    - While implementing the required changes for the popup modal on
>    desktop devices, you have broken the popup modal design for mobile devices.
>    Kindly ensure that the width on mobile devices corresponds to the given
>    figma design template 👍
>
> Your Previous Design
>
>
> <https://user-images.githubusercontent.com/46839548/188840253-dad6d276-c8de-4bac-9e67-853887a8e79c.png>
> Your Current Design
>
> [image: image]
> <https://user-images.githubusercontent.com/46839548/188841611-176cd116-4b2a-431f-9291-1808872e5aea.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AshwinCarvalho999/Portfolio-details-popup-window/pull/1#pullrequestreview-1098827296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVKQBYVFLDGFDGXLEMBS5H3V5BNCVANCNFSM6AAAAAAQF3QO44>
> .
> You are receiving this because you were mentioned.Message ID:
> <AshwinCarvalho999/Portfolio-details-popup-window/pull/1/review/1098827296
> @github.com>
>

2022-09-07 13:25 UTC, AshwinCarvalho999 commented
Awesome, thanks!

On Wed, Sep 7, 2022, 6:47 PM Zerradi Amine ***@***.***> wrote:

> ***@***.**** approved this pull request.
> *Hi @AshwinCarvalho999 <https://github.com/AshwinCarvalho999>,* *Congratulations!
> 🎉*
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it 🚀 :
> *Note*
>
>    - *Please add a getting started section to your readme file even if
>    it's a personal project.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AshwinCarvalho999/Portfolio-details-popup-window/pull/1#pullrequestreview-1099158015>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVKQBYXDWVRGC5FGBR3E2TLV5CIV7ANCNFSM6AAAAAAQF3QO44>
> .
> You are receiving this because you were mentioned.Message ID:
> <AshwinCarvalho999/Portfolio-details-popup-window/pull/1/review/1099158015
> @github.com>
>

2022-09-07 13:33 UTC, merged